### ISSUE TITLE
sendtoClient导致的baseapp 崩溃

### ISSUE THREAD

**Issue by luozhonghai** [kbengine/kbengine#1564]
Core was generated by `/www/kbengine-2.4.5/kbe/bin/server//baseapp --cid=6129652375332859700 --gus=7'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000000006fedcb in KBEngine::Proxy::sendToClient (this=<optimized out>, expectData=false) at proxy.cpp:806
806             Network::Channel* pChannel = clientEntityCall()->getChannel();
(gdb) where
#0  0x00000000006fedcb in KBEngine::Proxy::sendToClient (this=<optimized out>, expectData=false) at proxy.cpp:806
#1  0x00000000007a93e6 in triggerTimer (this=0x7fbb94fddb80) at /www/kbengine-2.4.5/kbe/src/lib/common/timer.inl:249
#2  KBEngine::TimersT<unsigned long>::process (this=0x7fbb9ce18560, now=201955013290496333)
    at /www/kbengine-2.4.5/kbe/src/lib/common/timer.inl:121
#3  0x00000000007a8cfb in KBEngine::Network::EventDispatcher::processTimers (this=this@entry=0x7ffc2c253ca0) at event_dispatcher.cpp:
#4  0x00000000007a8edb in KBEngine::Network::EventDispatcher::processOnce (this=this@entry=0x7ffc2c253ca0, shouldIdle=shouldIdle@entr
    at event_dispatcher.cpp:197
#5  0x00000000007a8f2d in KBEngine::Network::EventDispatcher::processUntilBreak (this=0x7ffc2c253ca0) at event_dispatcher.cpp:184
#6  0x000000000071427d in KBEngine::ServerApp::run (this=this@entry=0x7ffc2c253f50) at serverapp.cpp:259
#7  0x0000000000699695 in KBEngine::Baseapp::run (this=this@entry=0x7ffc2c253f50) at baseapp.cpp:533
#8  0x00000000006fc875 in KBEngine::kbeMainT<KBEngine::Baseapp> (argc=<optimized out>, argv=<optimized out>,
    componentType=componentType@entry=KBEngine::BASEAPP_TYPE, extlisteningTcpPort_min=<optimized out>, extlisteningTcpPort_max=20019,
    extlisteningUdpPort_min=20005, extlisteningUdpPort_max=20009, extlisteningInterface=0x127607a <KBEngine::g_serverConfig+3242> "",
    intlisteningPort=intlisteningPort@entry=0, intlisteningInterface=0x1275f7a <KBEngine::g_serverConfig+2986> "")
    at /www/kbengine-2.4.5/kbe/src/lib/server/kbemain.h:218
#9  0x00000000006dd44a in kbeMain (argc=<optimized out>, argv=<optimized out>) at main.cpp:63
#10 0x00007fbb9d35a555 in __libc_start_main (main=0x66c230 <main(int, char**)>, argc=3, argv=0x7ffc2c2544c8, init=<optimized out>,
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc2c2544b8) at ../csu/libc-start.c:266
#11 0x000000000067a874 in _start ()
****

![image](https://user-images.githubusercontent.com/6804338/178924086-3b10593d-e78d-4263-bf71-5763b5079738.png)

**Comment by luozhonghai** [comment]
![image](https://user-images.githubusercontent.com/6804338/178924252-fa3dc00c-7124-4416-9f81-b2413673e57e.png)

**Comment by luozhonghai** [comment]
感觉baseapp 太容易崩溃了， 看了代码

![image](https://user-images.githubusercontent.com/6804338/178924499-27586859-73ce-41d4-a5a2-c8a2efc7e76d.png)

这行为啥会导致崩溃。上一行已经判断了ClientEntityCall是否有效了。

**Comment by the-tuxedo-cat** [comment]
do you have assertions enabled?
