### ISSUE TITLE
cellapp初始化时不应该执行其他进程要求的任务

### ISSUE THREAD

**Issue by kbengine** [kbengine/kbengine#198]
INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 032] - Resmgr::initialize: KBE_ROOT=C:/kbengine/
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 033] - Resmgr::initialize: KBE_RES_PATH=C:/kbengine/kbe/res/;C:/kbengine/assets/;C:/kbengine/assets/scripts/;C:/kbengine/assets/res/
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 033] - Resmgr::initialize: KBE_BIN_PATH=C:/kbengine/kbe/bin/server/
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 062] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on eth0 ( 192.168.1.115:3167 )
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 063] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.1.115:3167, SOMAXCONN=5.
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 063] - server-configs:
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 063] - 	gameUpdateHertz : 10
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 063] - 	defaultAoIRadius : 80
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 063] - 	defaultAoIHysteresisArea : 5
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 063] - 	entryScriptFile : kbengine
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 063] - 	internalAddr : 192.168.1.115:3167
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 063] - 	componentID : 7129652375332859701
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 068] - ---- cellapp Version: 0.3.0. ScriptVersion: 0.1.0. Protocol: 0767B8ECC03A3A4090FD611A62FAEB6A. Config: Release. Built: 08:53:40 Jan  5 2015. AppID: 7129652375332859701. UID: 115. PID: 5648 ----
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 069] - Server xwd888: AMD Athlon(tm) 64 X2 Dual Core Processor 4200+ with 2097151kB RAM
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 070] - ThreadPool::createThreadPool: creating  threadpool...
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 070] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
   DEBUG    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 231] - Script::install_py_dlls(): PyInit_pyexpat
   DEBUG    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 231] - Script::install_py_dlls(): PyInit__socket
   DEBUG    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 232] - Script::install_py_dlls(): PyInit__hashlib
   DEBUG    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 233] - Script::install_py_dlls(): PyInit_select
   DEBUG    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 233] - Script::install_py_dlls(): PyInit__ctypes
   DEBUG    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 234] - Script::install_py_dlls(): PyInit__elementtree
   DEBUG    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 318] - Script::install_py_dlls(): PyInit_unicodedata
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 395] - Script::install(): is successfully, Python=(3.4.2 (default, Jan  5 2015, 08:55:14) [MSC v.1800 32 bit (Intel)])!
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 396] - Script::install(): KBExtra is successfully!
   DEBUG    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 513] - loaded script:Account(1).
   DEBUG    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 578] - loaded script:Avatar(2).
   DEBUG    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 607] - loaded script:Space(4).
   DEBUG    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 611] - loaded script:SpaceDuplicate(5).
   DEBUG    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 614] - loaded script:SpawnPoint(6).
   DEBUG    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 624] - loaded script:Monster(7).
   DEBUG    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 628] - loaded script:NPC(8).
   DEBUG    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 631] - loaded script:Gate(9).
   DEBUG    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 642] - loaded script:RefreshPoint(12).
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 646] - TelnetServer server is running on port 50001
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 683] - ---- cellapp is running ----
   DEBUG    cellapp02 115 7129652375332859701  [2015-01-06 11:01:57 684] - Components::process(): Request for the process of identity...
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:04 784] - Components::findInterfaces: finding logger(1)...
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:04 900] - Components::findInterfaces: found logger, addr:192.168.1.115:3094
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:04 900] - Components::addComponent[logger], uid=115, componentID=1129653375331859700, globalorderid=2, grouporderid=1, totalcount=1
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:04 914] - Components::findInterfaces: finding dbmgr(2)...
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:04 949] - Components::findInterfaces: found logger, addr:192.168.1.115:3094
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:05 101] - Components::findInterfaces: found dbmgr, addr:192.168.1.115:3097
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:05 101] - Components::addComponent[dbmgr], uid=115, componentID=3129652375332859700, globalorderid=4, grouporderid=1, totalcount=1
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:05 150] - Components::findInterfaces: found dbmgr, addr:192.168.1.115:3097
    INFO    cellapp01 115 7129652375332859700  [2015-01-06 11:02:06 070] - Components::findInterfaces: finding baseappmgr(1)...
    INFO    cellapp01 115 7129652375332859700  [2015-01-06 11:02:06 239] - Components::findInterfaces: found baseappmgr, addr:192.168.1.115:3098
    INFO    cellapp01 115 7129652375332859700  [2015-01-06 11:02:06 239] - Components::addComponent[baseappmgr], uid=115, componentID=4129652375332859700, globalorderid=5, grouporderid=1, totalcount=1
    INFO    cellapp01 115 7129652375332859700  [2015-01-06 11:02:06 351] - Components::findInterfaces: found baseappmgr, addr:192.168.1.115:3098
    INFO    cellapp01 115 7129652375332859700  [2015-01-06 11:02:08 470] - Components::findInterfaces: register self to dbmgr...
    INFO    cellapp01 115 7129652375332859700  [2015-01-06 11:02:08 476] - Components::findInterfaces: register self to cellappmgr...
    INFO    cellapp01 115 7129652375332859700  [2015-01-06 11:02:08 537] - Components::findInterfaces: register self to baseappmgr...
    INFO    cellapp01 115 7129652375332859700  [2015-01-06 11:02:08 539] - Components::process(): Found all the components!
    INFO    cellapp01 115 7129652375332859700  [2015-01-06 11:02:08 570] - ServerApp::onRegisterNewApp: uid:115, username:xwd888, componentType:baseapp, componentID:6129652375332859700, globalorderID=7, grouporderID=1, intaddr:192.168.1.115, intport:3154, extaddr:192.168.1.115, extport:20015,  from 192.168.1.115:3183/0/0/0.
    INFO    cellapp01 115 7129652375332859700  [2015-01-06 11:02:08 570] - Components::addComponent[baseapp], uid=115, componentID=6129652375332859700, globalorderid=7, grouporderid=1, totalcount=1
    INFO    cellapp01 115 7129652375332859700  [2015-01-06 11:02:08 570] - ServerApp::onRegisterNewApp: uid:115, username:xwd888, componentType:baseapp, componentID:6129652375332859700, globalorderID=7, grouporderID=1, intaddr:192.168.1.115, intport:3154, extaddr:192.168.1.115, extport:20015,  from 192.168.1.115:3183/0/0/0.
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:07 184] - Components::findInterfaces: finding cellappmgr(1)...
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:07 588] - Components::findInterfaces: found cellappmgr, addr:192.168.1.115:3153
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:07 588] - Components::addComponent[cellappmgr], uid=115, componentID=5129652375332859700, globalorderid=6, grouporderid=1, totalcount=1
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:07 637] - Components::findInterfaces: found cellappmgr, addr:192.168.1.115:3153
   DEBUG    cellapp01 115 7129652375332859700  [2015-01-06 11:02:08 670] - Spaces::createNewSpace: new space 1.
    INFO    cellapp01 115 7129652375332859700  [2015-01-06 11:02:08 670] - EntityApp::createEntity: new Space 3
    INFO    cellapp01 115 7129652375332859700  [2015-01-06 11:02:08 670] - KBEngine::addSpaceGeometryMapping: spaceID=1, respath=fengmingzhen, shouldLoadOnServer=1!
   S_DBG    cellapp01 115 7129652375332859700  [2015-01-06 11:02:08 670] - onSpaceData: spaceID=1, key=_mapping, value=fengmingzhen.
   S_DBG    cellapp01 115 7129652375332859700  [2015-01-06 11:02:08 670] - created space[1] entityID = 3, res = fengmingzhen.
    INFO    cellapp01 115 7129652375332859700  [2015-01-06 11:02:08 770] - KBEngine::onLoadedSpaceGeometryMapping: spaceID=1, respath=fengmingzhen!
   S_DBG    cellapp01 115 7129652375332859700  [2015-01-06 11:02:08 770] - onSpaceGeometryLoaded: spaceID=1, mapping=fengmingzhen.
   S_DBG    cellapp01 115 7129652375332859700  [2015-01-06 11:02:08 770] - onAllSpaceGeometryLoaded: spaceID=1, isBootstrap=1, mapping=fengmingzhen.
    INFO    cellapp01 115 7129652375332859700  [2015-01-06 11:02:08 970] - EntityApp::createEntity: new SpawnPoint 4
   S_DBG    cellapp01 115 7129652375332859700  [2015-01-06 11:02:08 970] - SpawnPoint::__init__: 4
   S_ERR    cellapp01 115 7129652375332859700  [2015-01-06 11:02:09 970] - SystemError: EntityApp::createEntity: is Failed. not enough entityIDs.
   S_ERR    cellapp01 115 7129652375332859700  [2015-01-06 11:02:09 979] - Traceback (most recent call last):
  File "C:/kbengine/assets/scripts/cell\interfaces\GameObject.py", line 54, in onTimer
    self._timermap[userArg](self, tid, userArg)
   S_ERR    cellapp01 115 7129652375332859700  [2015-01-06 11:02:09 982] -   File "C:/kbengine/assets/scripts/cell\SpawnPoint.py", line 70, in spawnTimer
    KBEngine.createEntity(datas["entityType"], self.spaceID, tuple(self.position), tuple(self.direction), params)
   S_ERR    cellapp01 115 7129652375332859700  [2015-01-06 11:02:09 984] - SystemError: error return without exception set
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:09 684] - Components::findInterfaces: finding baseappmgr(1)...
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:09 781] - Components::findInterfaces: found baseappmgr, addr:192.168.1.115:3098
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:09 781] - Components::addComponent[baseappmgr], uid=115, componentID=4129652375332859700, globalorderid=5, grouporderid=1, totalcount=1
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:09 830] - Components::findInterfaces: found baseappmgr, addr:192.168.1.115:3098
   S_DBG    cellapp01 115 7129652375332859700  [2015-01-06 11:02:11 570] - onGlobalData: RoomMgr
   S_DBG    cellapp01 115 7129652375332859700  [2015-01-06 11:02:11 570] - onGlobalData: SpaceMgr
   S_DBG    cellapp01 115 7129652375332859700  [2015-01-06 11:02:11 571] - onGlobalData: space_1
    INFO    cellapp01 115 7129652375332859700  [2015-01-06 11:02:11 571] - EntityApp::onDbmgrInitCompleted: entityID alloc(1025-2049), startGlobalOrder=8, startGroupOrder=1, digest=7A84A5D35748173C81F1C3E97091D735.
    INFO    cellapp01 115 7129652375332859700  [2015-01-06 11:02:11 571] - IDClient::onAddRange: number of ids increased from 1025 to 2049.
   S_DBG    cellapp01 115 7129652375332859700  [2015-01-06 11:02:11 571] - onInit::isReload:0
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:11 902] - Components::findInterfaces: register self to dbmgr...
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:11 934] - Components::findInterfaces: register self to cellappmgr...
    INFO    cellapp01 115 7129652375332859700  [2015-01-06 11:02:11 970] - ServerApp::onRegisterNewApp: uid:115, username:xwd888, componentType:cellapp, componentID:7129652375332859701, globalorderID=81, grouporderID=2, intaddr:192.168.1.115, intport:3167, extaddr:nonsupport, extport:0,  from 192.168.1.115:3097/0/0/0.
    INFO    cellapp01 115 7129652375332859700  [2015-01-06 11:02:11 970] - Components::addComponent[cellapp], uid=115, componentID=7129652375332859701, globalorderid=81, grouporderid=2, totalcount=1
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:11 937] - Components::findInterfaces: register self to baseappmgr...
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:11 938] - Components::process(): Found all the components!
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:11 984] - ServerApp::onRegisterNewApp: uid:115, username:xwd888, componentType:baseapp, componentID:6129652375332859700, globalorderID=7, grouporderID=1, intaddr:192.168.1.115, intport:3154, extaddr:192.168.1.115, extport:20015,  from 192.168.1.115:3188/0/0/0.
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:11 984] - Components::addComponent[baseapp], uid=115, componentID=6129652375332859700, globalorderid=7, grouporderid=1, totalcount=1
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:11 984] - ServerApp::onRegisterNewApp: uid:115, username:xwd888, componentType:baseapp, componentID:6129652375332859700, globalorderID=7, grouporderID=1, intaddr:192.168.1.115, intport:3154, extaddr:192.168.1.115, extport:20015,  from 192.168.1.115:3188/0/0/0.
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:11 984] - ServerApp::onRegisterNewApp: uid:115, username:xwd888, componentType:cellapp, componentID:7129652375332859700, globalorderID=8, grouporderID=1, intaddr:192.168.1.115, intport:3162, extaddr:nonsupport, extport:0,  from 192.168.1.115:3190/0/0/0.
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:11 984] - Components::addComponent[cellapp], uid=115, componentID=7129652375332859700, globalorderid=8, grouporderid=1, totalcount=1
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:11 984] - ServerApp::onRegisterNewApp: uid:115, username:xwd888, componentType:cellapp, componentID:7129652375332859700, globalorderID=8, grouporderID=1, intaddr:192.168.1.115, intport:3162, extaddr:nonsupport, extport:0,  from 192.168.1.115:3190/0/0/0.
    INFO    cellapp01 115 7129652375332859700  [2015-01-06 11:02:12 270] - ServerApp::onRegisterNewApp: uid:115, username:xwd888, componentType:baseapp, componentID:6129652375332859701, globalorderID=71, grouporderID=2, intaddr:192.168.1.115, intport:3166, extaddr:192.168.1.115, extport:20016,  from 192.168.1.115:3097/0/0/0.
    INFO    cellapp01 115 7129652375332859700  [2015-01-06 11:02:12 270] - Components::addComponent[baseapp], uid=115, componentID=6129652375332859701, globalorderid=71, grouporderid=2, totalcount=2
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:12 284] - ServerApp::onRegisterNewApp: uid:115, username:xwd888, componentType:baseapp, componentID:6129652375332859701, globalorderID=71, grouporderID=2, intaddr:192.168.1.115, intport:3166, extaddr:192.168.1.115, extport:20016,  from 192.168.1.115:3097/0/0/0.
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:12 284] - Components::addComponent[baseapp], uid=115, componentID=6129652375332859701, globalorderid=71, grouporderid=2, totalcount=2
   S_DBG    cellapp02 115 7129652375332859701  [2015-01-06 11:02:15 284] - onGlobalData: RoomMgr
   S_DBG    cellapp02 115 7129652375332859701  [2015-01-06 11:02:15 284] - onGlobalData: SpaceMgr
   S_DBG    cellapp02 115 7129652375332859701  [2015-01-06 11:02:15 285] - onGlobalData: space_1
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:15 285] - EntityApp::onDbmgrInitCompleted: entityID alloc(2049-3073), startGlobalOrder=81, startGroupOrder=2, digest=7A84A5D35748173C81F1C3E97091D735.
    INFO    cellapp02 115 7129652375332859701  [2015-01-06 11:02:15 285] - IDClient::onAddRange: number of ids increased from 2049 to 3073.
   S_DBG    cellapp02 115 7129652375332859701  [2015-01-06 11:02:15 285] - onInit::isReload:0
   S_DBG    cellapp01 115 7129652375332859700  [2015-01-06 11:02:15 570] - onGlobalData: RankListMgr
   S_DBG    cellapp02 115 7129652375332859701  [2015-01-06 11:02:15 584] - onGlobalData: RankListMgr

**Comment by kbengine** [comment]
Cellappmgr::reqCreateInNewSpace 需要控制
