### ISSUE TITLE
test_distutils failed

### ISSUE THREAD

**Issue by kebiao** [kbengine/kbengine#969]
进入引擎python源码目录执行
./python -m test.regrtest test_distutils -W 等测试到email的时候会提示失败。
但不知道具体原因, 可对比原版python的测试结果

**Comment by kebiao** [comment]
root@kbe-VirtualBox:/home/kbe/kbengine/kbe/src/lib/python# ./python -m test.regrtest test_distutils -W
Run tests sequentially
0:00:00 load avg: 0.67 [1/1] test_distutils
test_get_exe_bytes (distutils.tests.test_bdist_wininst.BuildWinInstTestCase) ... ERROR
test_osx_cc_overrides_ldshared (distutils.tests.test_unixccompiler.UnixCCompilerTestCase) ... skipped 'test only relevant for OS X'
test_osx_explicit_ldshared (distutils.tests.test_unixccompiler.UnixCCompilerTestCase) ... skipped 'test only relevant for OS X'
test_runtime_libdir_option (distutils.tests.test_unixccompiler.UnixCCompilerTestCase) ... ok
test_check_archive_formats (distutils.tests.test_archive_util.ArchiveUtilTestCase) ... ok
test_compress_deprecated (distutils.tests.test_archive_util.ArchiveUtilTestCase) ... skipped 'The compress program is required'
test_make_archive (distutils.tests.test_archive_util.ArchiveUtilTestCase) ... ok
test_make_archive_bztar (distutils.tests.test_archive_util.ArchiveUtilTestCase) ... skipped 'Need bz2 support to run'
test_make_archive_cwd (distutils.tests.test_archive_util.ArchiveUtilTestCase) ... ok
test_make_archive_gztar (distutils.tests.test_archive_util.ArchiveUtilTestCase) ... ok
test_make_archive_owner_group (distutils.tests.test_archive_util.ArchiveUtilTestCase) ... ok
test_make_archive_tar (distutils.tests.test_archive_util.ArchiveUtilTestCase) ... ok
test_make_archive_xztar (distutils.tests.test_archive_util.ArchiveUtilTestCase) ... skipped 'Need xz support to run'
test_make_tarball (distutils.tests.test_archive_util.ArchiveUtilTestCase) ... ok
test_make_tarball_bzip2 (distutils.tests.test_archive_util.ArchiveUtilTestCase) ... skipped 'Need bz2 support to run'
test_make_tarball_extended (distutils.tests.test_archive_util.ArchiveUtilTestCase) ... ok
test_make_tarball_gzip (distutils.tests.test_archive_util.ArchiveUtilTestCase) ... ok
test_make_tarball_latin1 (distutils.tests.test_archive_util.ArchiveUtilTestCase) ... ok
test_make_tarball_xz (distutils.tests.test_archive_util.ArchiveUtilTestCase) ... skipped 'Need lzma support to run'
test_make_zipfile (distutils.tests.test_archive_util.ArchiveUtilTestCase) ... ok
test_make_zipfile_no_zlib (distutils.tests.test_archive_util.ArchiveUtilTestCase) ... ok
test_tarfile_root_owner (distutils.tests.test_archive_util.ArchiveUtilTestCase) ... ok
test_tarfile_vs_tar (distutils.tests.test_archive_util.ArchiveUtilTestCase) ... ok
test_change_root (distutils.tests.test_util.UtilTestCase) ... ok
test_check_environ (distutils.tests.test_util.UtilTestCase) ... ok
test_convert_path (distutils.tests.test_util.UtilTestCase) ... ok
test_dont_write_bytecode (distutils.tests.test_util.UtilTestCase) ... ok
test_get_platform (distutils.tests.test_util.UtilTestCase) ... ok
test_grok_environment_error (distutils.tests.test_util.UtilTestCase) ... ok
test_rfc822_escape (distutils.tests.test_util.UtilTestCase) ... ok
test_split_quoted (distutils.tests.test_util.UtilTestCase) ... ok
test_strtobool (distutils.tests.test_util.UtilTestCase) ... ok
test_debug_print (distutils.tests.test_cmd.CommandTestCase) ... ok
test_dump_options (distutils.tests.test_cmd.CommandTestCase) ... ok
test_ensure_dirname (distutils.tests.test_cmd.CommandTestCase) ... ok
test_ensure_filename (distutils.tests.test_cmd.CommandTestCase) ... ok
test_ensure_string (distutils.tests.test_cmd.CommandTestCase) ... ok
test_ensure_string_list (distutils.tests.test_cmd.CommandTestCase) ... ok
test_make_file (distutils.tests.test_cmd.CommandTestCase) ... ok
test_clean (distutils.tests.test_config_cmd.ConfigTestCase) ... ok
test_dump_file (distutils.tests.test_config_cmd.ConfigTestCase) ... ok
test_finalize_options (distutils.tests.test_config_cmd.ConfigTestCase) ... ok
test_search_cpp (distutils.tests.test_config_cmd.ConfigTestCase) ... ok
test_build_libraries (distutils.tests.test_build_clib.BuildCLibTestCase) ... ok
test_check_library_dist (distutils.tests.test_build_clib.BuildCLibTestCase) ... ok
test_finalize_options (distutils.tests.test_build_clib.BuildCLibTestCase) ... ok
test_get_source_files (distutils.tests.test_build_clib.BuildCLibTestCase) ... ok
test_run (distutils.tests.test_build_clib.BuildCLibTestCase) ... ok
test_cmp (distutils.tests.test_version.VersionTestCase) ... ok
test_cmp_strict (distutils.tests.test_version.VersionTestCase) ... ok
test_prerelease (distutils.tests.test_version.VersionTestCase) ... ok
test_build_ext (distutils.tests.test_build_ext.BuildExtTestCase) ... ok
test_check_extensions_list (distutils.tests.test_build_ext.BuildExtTestCase) ... ok
test_compiler_option (distutils.tests.test_build_ext.BuildExtTestCase) ... ok
test_deployment_target_default (distutils.tests.test_build_ext.BuildExtTestCase) ... skipped 'test only relevant for MacOSX'
test_deployment_target_higher_ok (distutils.tests.test_build_ext.BuildExtTestCase) ... skipped 'test only relevant for MacOSX'
test_deployment_target_too_low (distutils.tests.test_build_ext.BuildExtTestCase) ... skipped 'test only relevant for MacOSX'
test_ext_fullpath (distutils.tests.test_build_ext.BuildExtTestCase) ... ok
test_finalize_options (distutils.tests.test_build_ext.BuildExtTestCase) ... ok
test_get_outputs (distutils.tests.test_build_ext.BuildExtTestCase) ... ok
test_get_source_files (distutils.tests.test_build_ext.BuildExtTestCase) ... ok
test_optional_extension (distutils.tests.test_build_ext.BuildExtTestCase) ... ok
test_solaris_enable_shared (distutils.tests.test_build_ext.BuildExtTestCase) ... ok
test_user_site (distutils.tests.test_build_ext.BuildExtTestCase) ... ok
test_build_ext (distutils.tests.test_build_ext.ParallelBuildExtTestCase) ... skipped 'Already tested in BuildExtTestCase'
test_check_extensions_list (distutils.tests.test_build_ext.ParallelBuildExtTestCase) ... ok
test_compiler_option (distutils.tests.test_build_ext.ParallelBuildExtTestCase) ... ok
test_deployment_target_default (distutils.tests.test_build_ext.ParallelBuildExtTestCase) ... skipped 'test only relevant for MacOSX'
test_deployment_target_higher_ok (distutils.tests.test_build_ext.ParallelBuildExtTestCase) ... skipped 'test only relevant for MacOSX'
test_deployment_target_too_low (distutils.tests.test_build_ext.ParallelBuildExtTestCase) ... skipped 'test only relevant for MacOSX'
test_ext_fullpath (distutils.tests.test_build_ext.ParallelBuildExtTestCase) ... ok
test_finalize_options (distutils.tests.test_build_ext.ParallelBuildExtTestCase) ... ok
test_get_outputs (distutils.tests.test_build_ext.ParallelBuildExtTestCase) ... ok
test_get_source_files (distutils.tests.test_build_ext.ParallelBuildExtTestCase) ... ok
test_optional_extension (distutils.tests.test_build_ext.ParallelBuildExtTestCase) ... ok
test_solaris_enable_shared (distutils.tests.test_build_ext.ParallelBuildExtTestCase) ... ok
test_user_site (distutils.tests.test_build_ext.ParallelBuildExtTestCase) ... ok
test_build (distutils.tests.test_build_scripts.BuildScriptsTestCase) ... ok
test_default_settings (distutils.tests.test_build_scripts.BuildScriptsTestCase) ... ok
test_version_int (distutils.tests.test_build_scripts.BuildScriptsTestCase) ... ok
test_simple_run (distutils.tests.test_install_data.InstallDataTestCase) ... ok
test_default_settings (distutils.tests.test_install_scripts.InstallScriptsTestCase) ... ok
test_installation (distutils.tests.test_install_scripts.InstallScriptsTestCase) ... ok
test_copy_tree_exception_in_listdir (distutils.tests.test_dir_util.DirUtilTestCase) ... ok
test_copy_tree_skips_nfs_temp_files (distutils.tests.test_dir_util.DirUtilTestCase) ... ok
test_copy_tree_verbosity (distutils.tests.test_dir_util.DirUtilTestCase) ... ok
test_create_tree_verbosity (distutils.tests.test_dir_util.DirUtilTestCase) ... ok
test_ensure_relative (distutils.tests.test_dir_util.DirUtilTestCase) ... ok
test_mkpath_remove_tree_verbosity (distutils.tests.test_dir_util.DirUtilTestCase) ... ok
test_mkpath_with_custom_mode (distutils.tests.test_dir_util.DirUtilTestCase) ... ok
test_no_optimize_flag (distutils.tests.test_bdist_rpm.BuildRpmTestCase) ... ok
test_quiet (distutils.tests.test_bdist_rpm.BuildRpmTestCase) ... ok
test_debug_mode (distutils.tests.test_install.InstallTestCase) ... ok
test_finalize_options (distutils.tests.test_install.InstallTestCase) ... ok
test_handle_extra_path (distutils.tests.test_install.InstallTestCase) ... ok
test_home_installation_scheme (distutils.tests.test_install.InstallTestCase) ... ok
test_record (distutils.tests.test_install.InstallTestCase) ... ok
test_record_extensions (distutils.tests.test_install.InstallTestCase) ... ok
test_user_site (distutils.tests.test_install.InstallTestCase) ... ok
test_newer (distutils.tests.test_dep_util.DepUtilTestCase) ... ok
test_newer_group (distutils.tests.test_dep_util.DepUtilTestCase) ... ok
test_newer_pairwise (distutils.tests.test_dep_util.DepUtilTestCase) ... ok
test_add_defaults (distutils.tests.test_sdist.SDistTestCase) ... ok
test_check_metadata_deprecated (distutils.tests.test_sdist.SDistTestCase) ... ok
test_finalize_options (distutils.tests.test_sdist.SDistTestCase) ... ok
test_get_file_list (distutils.tests.test_sdist.SDistTestCase) ... ok
test_invalid_template_unknown_command (distutils.tests.test_sdist.SDistTestCase) ... ok
test_invalid_template_wrong_arguments (distutils.tests.test_sdist.SDistTestCase) ... ok
test_invalid_template_wrong_path (distutils.tests.test_sdist.SDistTestCase) ... skipped 'test relevant for Windows only'
test_make_distribution (distutils.tests.test_sdist.SDistTestCase) ... ok
test_make_distribution_owner_group (distutils.tests.test_sdist.SDistTestCase) ... ok
test_manifest_comments (distutils.tests.test_sdist.SDistTestCase) ... ok
test_manifest_marker (distutils.tests.test_sdist.SDistTestCase) ... ok
test_manual_manifest (distutils.tests.test_sdist.SDistTestCase) ... ok
test_metadata_check_option (distutils.tests.test_sdist.SDistTestCase) ... ok
test_prune_file_list (distutils.tests.test_sdist.SDistTestCase) ... ok
test_show_formats (distutils.tests.test_sdist.SDistTestCase) ... ok
test_check_config_h (distutils.tests.test_cygwinccompiler.CygwinCCompilerTestCase) ... ok
test_get_msvcr (distutils.tests.test_cygwinccompiler.CygwinCCompilerTestCase) ... ok
test_get_versions (distutils.tests.test_cygwinccompiler.CygwinCCompilerTestCase) ... ok
test_simple_run (distutils.tests.test_install_headers.InstallHeadersTestCase) ... ok
test_SO_deprecation (distutils.tests.test_sysconfig.SysconfigTestCase) ... ok
test_SO_in_vars (distutils.tests.test_sysconfig.SysconfigTestCase) ... ok
test_SO_value (distutils.tests.test_sysconfig.SysconfigTestCase) ... ok
test_customize_compiler (distutils.tests.test_sysconfig.SysconfigTestCase) ... ok
test_customize_compiler_before_get_config_vars (distutils.tests.test_sysconfig.SysconfigTestCase) ... ok
test_get_config_h_filename (distutils.tests.test_sysconfig.SysconfigTestCase) ... ok
test_get_config_vars (distutils.tests.test_sysconfig.SysconfigTestCase) ... ok
test_get_python_lib (distutils.tests.test_sysconfig.SysconfigTestCase) ... ok
test_parse_makefile_base (distutils.tests.test_sysconfig.SysconfigTestCase) ... ok
test_parse_makefile_literal_dollar (distutils.tests.test_sysconfig.SysconfigTestCase) ... ok
test_srcdir (distutils.tests.test_sysconfig.SysconfigTestCase) ... ok
test_srcdir_independent_of_cwd (distutils.tests.test_sysconfig.SysconfigTestCase) ... ok
test_sysconfig_compiler_vars (distutils.tests.test_sysconfig.SysconfigTestCase) ... ok
test_sysconfig_module (distutils.tests.test_sysconfig.SysconfigTestCase) ... ok
test_find_executable (distutils.tests.test_spawn.SpawnTestCase) ... ok
test_nt_quote_args (distutils.tests.test_spawn.SpawnTestCase) ... ok
test_spawn (distutils.tests.test_spawn.SpawnTestCase) ... ok
test_finalize_options (distutils.tests.test_upload.uploadTestCase) ... ok
test_saved_password (distutils.tests.test_upload.uploadTestCase) ... ok
test_upload (distutils.tests.test_upload.uploadTestCase) ... ok
test_upload_correct_cr (distutils.tests.test_upload.uploadTestCase) ... ok
test_upload_fails (distutils.tests.test_upload.uploadTestCase) ... ok
test_wrong_exception_order (distutils.tests.test_upload.uploadTestCase) ... ok
test_debug_print (distutils.tests.test_filelist.FileListTestCase) ... ok
test_exclude_pattern (distutils.tests.test_filelist.FileListTestCase) ... ok
test_glob_to_re (distutils.tests.test_filelist.FileListTestCase) ... ok
test_include_pattern (distutils.tests.test_filelist.FileListTestCase) ... ok
test_process_template (distutils.tests.test_filelist.FileListTestCase) ... ok
test_process_template_line (distutils.tests.test_filelist.FileListTestCase) ... ok
test_remove_duplicates (distutils.tests.test_filelist.FileListTestCase) ... ok
test_set_allfiles (distutils.tests.test_filelist.FileListTestCase) ... ok
test_translate_pattern (distutils.tests.test_filelist.FileListTestCase) ... ok
test_basic_discovery (distutils.tests.test_filelist.FindAllTestCase) ... ok
test_missing_symlink (distutils.tests.test_filelist.FindAllTestCase) ... ok
test_non_local_discovery (distutils.tests.test_filelist.FindAllTestCase) ... ok
test_minimal (distutils.tests.test_bdist_msi.BDistMSITestCase) ... skipped 'these tests require Windows'
test_no_compiler (distutils.tests.test_msvc9compiler.msvc9compilerTestCase) ... skipped 'These tests are only for win32'
test_reg_class (distutils.tests.test_msvc9compiler.msvc9compilerTestCase) ... skipped 'These tests are only for win32'
test_remove_entire_manifest (distutils.tests.test_msvc9compiler.msvc9compilerTestCase) ... skipped 'These tests are only for win32'
test_remove_visual_c_ref (distutils.tests.test_msvc9compiler.msvc9compilerTestCase) ... skipped 'These tests are only for win32'
test_simple_run (distutils.tests.test_clean.cleanTestCase) ... ok
test_debug_mode (distutils.tests.test_core.CoreTestCase) ... ok
test_run_setup_defines_subclass (distutils.tests.test_core.CoreTestCase) ... ok
test_run_setup_preserves_sys_argv (distutils.tests.test_core.CoreTestCase) ... ok
test_run_setup_provides_file (distutils.tests.test_core.CoreTestCase) ... ok
test_run_setup_uses_current_dir (distutils.tests.test_core.CoreTestCase) ... ok
test_formats (distutils.tests.test_bdist.BuildTestCase) ... ok
test_skip_build (distutils.tests.test_bdist.BuildTestCase) ... ok
test_finalize_options (distutils.tests.test_build.BuildTestCase) ... ok
test_config_interpolation (distutils.tests.test_config.PyPIRCCommandTestCase) ... ok
test_server_empty_registration (distutils.tests.test_config.PyPIRCCommandTestCase) ... ok
test_server_registration (distutils.tests.test_config.PyPIRCCommandTestCase) ... ok
test_simple_built (distutils.tests.test_bdist_dumb.BuildDumbTestCase) ... ok
test_copy_file_hard_link (distutils.tests.test_file_util.FileUtilTestCase) ... ok
test_copy_file_hard_link_failure (distutils.tests.test_file_util.FileUtilTestCase) ... ok
test_move_file_exception_unpacking_rename (distutils.tests.test_file_util.FileUtilTestCase) ... ok
test_move_file_exception_unpacking_unlink (distutils.tests.test_file_util.FileUtilTestCase) ... ok
test_move_file_verbosity (distutils.tests.test_file_util.FileUtilTestCase) ... ok
test_extension_init (distutils.tests.test_extension.ExtensionTestCase) ... ok
test_read_setup_file (distutils.tests.test_extension.ExtensionTestCase) ... ok
VersionPredicate (distutils.versionpredicate)
Doctest: distutils.versionpredicate.VersionPredicate ... ok
split_provision (distutils.versionpredicate)
Doctest: distutils.versionpredicate.split_provision ... ok
test_non_ascii (distutils.tests.test_log.TestLog) ... ok
test_byte_compile (distutils.tests.test_build_py.BuildPyTestCase) ... ok
test_byte_compile_optimized (distutils.tests.test_build_py.BuildPyTestCase) ... ok
test_dir_in_package_data (distutils.tests.test_build_py.BuildPyTestCase) ... ok
test_dont_write_bytecode (distutils.tests.test_build_py.BuildPyTestCase) ... ok
test_empty_package_dir (distutils.tests.test_build_py.BuildPyTestCase) ... ok
test_package_data (distutils.tests.test_build_py.BuildPyTestCase) ... ok
test_compiler_options (distutils.tests.test_msvccompiler.msvccompilerTestCase) ... skipped 'These tests are only for win32'
test_get_vc2015 (distutils.tests.test_msvccompiler.msvccompilerTestCase) ... skipped 'These tests are only for win32'
test_get_vc2017 (distutils.tests.test_msvccompiler.msvccompilerTestCase) ... skipped 'These tests are only for win32'
test_get_vc_env_unicode (distutils.tests.test_msvccompiler.msvccompilerTestCase) ... skipped 'These tests are only for win32'
test_no_compiler (distutils.tests.test_msvccompiler.msvccompilerTestCase) ... skipped 'These tests are only for win32'
test_vcruntime_copy (distutils.tests.test_msvccompiler.msvccompilerTestCase) ... skipped 'These tests are only for win32'
test_vcruntime_skip_copy (distutils.tests.test_msvccompiler.msvccompilerTestCase) ... skipped 'These tests are only for win32'
test_byte_compile (distutils.tests.test_install_lib.InstallLibTestCase) ... ok
test_dont_write_bytecode (distutils.tests.test_install_lib.InstallLibTestCase) ... ok
test_finalize_options (distutils.tests.test_install_lib.InstallLibTestCase) ... ok
test_get_inputs (distutils.tests.test_install_lib.InstallLibTestCase) ... ok
test_get_outputs (distutils.tests.test_install_lib.InstallLibTestCase) ... ok
test_announce (distutils.tests.test_dist.DistributionTestCase) ... ok
test_command_packages_cmdline (distutils.tests.test_dist.DistributionTestCase) ... ok
test_command_packages_configfile (distutils.tests.test_dist.DistributionTestCase) ... ok
test_command_packages_unspecified (distutils.tests.test_dist.DistributionTestCase) ... ok
test_empty_options (distutils.tests.test_dist.DistributionTestCase) ... ok
test_finalize_options (distutils.tests.test_dist.DistributionTestCase) ... ok
test_find_config_files_disable (distutils.tests.test_dist.DistributionTestCase) ... ok
test_get_command_packages (distutils.tests.test_dist.DistributionTestCase) ... ok
test_venv_install_options (distutils.tests.test_dist.DistributionTestCase) ... ok
test_classifier (distutils.tests.test_dist.MetadataTestCase) ... ok
test_classifier_invalid_type (distutils.tests.test_dist.MetadataTestCase) ... ok
test_custom_pydistutils (distutils.tests.test_dist.MetadataTestCase) ... ok
test_download_url (distutils.tests.test_dist.MetadataTestCase) ... ok
test_fix_help_options (distutils.tests.test_dist.MetadataTestCase) ... ok
test_keywords (distutils.tests.test_dist.MetadataTestCase) ... ok
test_keywords_invalid_type (distutils.tests.test_dist.MetadataTestCase) ... ok
test_long_description (distutils.tests.test_dist.MetadataTestCase) ... ok
test_obsoletes (distutils.tests.test_dist.MetadataTestCase) ... ok
test_obsoletes_illegal (distutils.tests.test_dist.MetadataTestCase) ... ok
test_obsoletes_to_list (distutils.tests.test_dist.MetadataTestCase) ... ok
test_platforms (distutils.tests.test_dist.MetadataTestCase) ... ok
test_platforms_invalid_types (distutils.tests.test_dist.MetadataTestCase) ... ok
test_provides (distutils.tests.test_dist.MetadataTestCase) ... ok
test_provides_illegal (distutils.tests.test_dist.MetadataTestCase) ... ok
test_read_metadata (distutils.tests.test_dist.MetadataTestCase) ... ok
test_requires (distutils.tests.test_dist.MetadataTestCase) ... ok
test_requires_illegal (distutils.tests.test_dist.MetadataTestCase) ... ok
test_requires_to_list (distutils.tests.test_dist.MetadataTestCase) ... ok
test_show_help (distutils.tests.test_dist.MetadataTestCase) ... ok
test_simple_metadata (distutils.tests.test_dist.MetadataTestCase) ... ok
test_check_all (distutils.tests.test_check.CheckTestCase) ... ok
test_check_document (distutils.tests.test_check.CheckTestCase) ... skipped "won't test without docutils"
test_check_metadata (distutils.tests.test_check.CheckTestCase) ... ok
test_check_restructuredtext (distutils.tests.test_check.CheckTestCase) ... skipped "won't test without docutils"
test_check_restructuredtext_with_syntax_highlight (distutils.tests.test_check.CheckTestCase) ... skipped "won't test without docutils"
test_class (distutils.tests.test_text_file.TextFileTestCase) ... ok
test_check_metadata_deprecated (distutils.tests.test_register.RegisterTestCase) ... ok
test_create_pypirc (distutils.tests.test_register.RegisterTestCase) ... ok
test_list_classifiers (distutils.tests.test_register.RegisterTestCase) ... ok
test_password_not_in_file (distutils.tests.test_register.RegisterTestCase) ... ok
test_password_reset (distutils.tests.test_register.RegisterTestCase) ... ok
test_register_invalid_long_description (distutils.tests.test_register.RegisterTestCase) ... skipped 'needs docutils'
test_registering (distutils.tests.test_register.RegisterTestCase) ... ok
test_show_response (distutils.tests.test_register.RegisterTestCase) ... ok
test_strict (distutils.tests.test_register.RegisterTestCase) ... skipped 'needs docutils'

======================================================================
ERROR: test_get_exe_bytes (distutils.tests.test_bdist_wininst.BuildWinInstTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kbe/kbengine/kbe/src/lib/python/Lib/distutils/tests/test_bdist_wininst.py", line 26, in test_get_exe_bytes
    exe_file = cmd.get_exe_bytes()
  File "/home/kbe/kbengine/kbe/src/lib/python/Lib/distutils/command/bdist_wininst.py", line 360, in get_exe_bytes
    f = open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/kbe/kbengine/kbe/src/lib/python/Lib/distutils/command/wininst-14.0.exe'

----------------------------------------------------------------------

Ran 247 tests in 1.597s

FAILED (errors=1, skipped=32)
test test_distutils failed
test_distutils failed

== Tests result: FAILURE ==

1 test failed:
    test_distutils

Total duration: 1 sec 784 ms
Tests result: FAILURE
