### ISSUE TITLE
test_import error

### ISSUE THREAD

**Issue by kebiao** [kbengine/kbengine#970]
root@kbe-VirtualBox:/home/kbe/kbengine/kbe/src/lib/python# ./python -m test.regrtest test_import -W
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Traceback (most recent call last):
  File "/home/kbe/kbengine/kbe/src/lib/python/Lib/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kbe/kbengine/kbe/src/lib/python/Lib/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kbe/kbengine/kbe/src/lib/python/Lib/test/regrtest.py", line 14, in <module>
    from test.libregrtest import main
  File "/home/kbe/kbengine/kbe/src/lib/python/Lib/test/libregrtest/__init__.py", line 4, in <module>
    from test.libregrtest.cmdline import _parse_args, RESOURCE_NAMES, ALL_RESOURCES
  File "/home/kbe/kbengine/kbe/src/lib/python/Lib/test/libregrtest/cmdline.py", line 4, in <module>
    from test import support
  File "/home/kbe/kbengine/kbe/src/lib/python/Lib/test/support/__init__.py", line 17, in <module>
    import logging.handlers
  File "/home/kbe/kbengine/kbe/src/lib/python/Lib/logging/handlers.py", line 28, in <module>
    import queue
  File "/home/kbe/kbengine/kbe/src/lib/python/Lib/queue.py", line 16, in <module>
    from _queue import Empty
ModuleNotFoundError: No module named '_queue'

sed 's/#include "zlib.h"/#if defined( __WIN32__ ) || defined( WIN32 ) || defined( _WIN32 )\n#define ZLIB_WINAPI\n#endif\n#include "zlib.h"\n/' zlibmodule.c -i

**Comment by kebiao** [comment]
root@kbe-VirtualBox:/home/kbe/kbengine/kbe/src/lib/python# ./python
Python 3.7.2 (default, Jan  1 2019, 22:10:21) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import _testcapi
>>> _testcapi.__file__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module '_testcapi' has no attribute '__file__'

**Comment by kebiao** [comment]
root@kbe-VirtualBox:/home/kbe/Python-3.7.2# ./python 
Python 3.7.2 (default, Jan  1 2019, 21:45:10) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import _testcapi
>>> _testcapi.__file__
'/home/kbe/Python-3.7.2/build/lib.linux-x86_64-3.7/_testcapi.cpython-37m-x86_64-linux-gnu.so'
>>>
